name: ir
definition: ./src
generators:
  - name: fernapi/fern-typescript
    version: local
    generate:
      enabled: true
      output: ./generated-ts
    config:
      mode: model
  - name: fernapi/fern-java
    version: 0.0.39
    generate: true
    config:
      packagePrefix: "com.fern"
      mode: MODEL
