name: fern-ir-types
definition: ./src
generators:
  - name: fernapi/fern-typescript
    version: 0.0.85
    output: ./fern-ir-typescript
    config:
      mode: model
  - name: fernapi/fern-java
    version: 0.0.31
    output: ./fern-ir-java/ir-api
    config:
      packagePrefix: "com.fern"
      mode: MODEL
