name: Fern Intermediate Representation
definition: ./src
generators:
  - name: fernapi/fern-typescript
    version: 0.0.74
    output: ./fern-ir-typescript/src/generated
    config:
      mode: model
    publish: npm
  - name: fernapi/fern-java
    version: 0.0.29
    output: ./fern-ir-java/ir-api
    config:
      packagePrefix: "com.fern"
      mode: MODEL
