name: fern-ir-types
definition: ./src
generators:
  - name: fernapi/fern-typescript
    version: 0.0.84
    output: ./fern-ir-typescript2
    config:
      mode: model
      packageName: "@fern-api/api"
  - name: fernapi/fern-java
    version: 0.0.29
    output: ./fern-ir-java/ir-api
    config:
      packagePrefix: "com.fern"
      mode: MODEL
