name: fern-ir-types
definition: ./src
generators:
  - name: fernapi/fern-typescript
    version: 0.0.104
    generate: true
    config:
      mode: model
  - name: fernapi/fern-java
    version: 0.0.39
    generate: true
    config:
      packagePrefix: "com.fern"
      mode: MODEL
