changesetBaseRefs:
  - main
  - origin/main

npmScopes:
  fern-fern:
    npmAuthToken: eyJ2ZXIiOjEsImlzdSI6MTY1NjEzMjU3MCwiZW5jIjoiQTEyOEdDTSIsInRhZyI6Il9heDA4TVgxeWNJQmQwekdpVkZObFEiLCJleHAiOjE2NTYxNzU3NzAsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiWldveDJJWHJMVUtiTnpYYiJ9.aKKJT5jNXlKg3ff_pkT4hA.lm7lBf1CODlNmYN1.lBlFeAn-lcuD8-ZX-TwYucIqLCz0pmGPyAKzmzmt7WGggvaa6e55uJ84N7YJSVqdgfmBJhlV5rVfps5_INJCbv1fKPitTfE1Oo5cBSA4-BNKI96oGEopOLgnpzpSUNNBgghmCrvsRiDtSs8Z05PFq6a1BFX_riwwX0tY1fKMjRXJKg8WTdwTC-LZb5HsX94y2KIZOEbm60yxTaz9B3gglx9NSMVY3Z5VFbOWEpUz0LBaeSkU4ZFYEtCh44xJ0rsT2fBO8C7_ZhSkL1TqAp-kALM4aNB-fdeL9H0p92sRJMhl04cehkKVq6L8VKhOmSLYTeYLFh4Cgfz4R7PHjARMrWWbk1jVN9LhjF4D8q_NlZLrosTaDOKvxd63UFDGYrP2e804eJab3vogj65dxc42hpYJa_csI1pGG1zA08sD5XP9IdtZKpPYeWcdK7LYzFb8VtdzVMWRw-meKkNfX4WVDo9mL0JfUmfvFbDrj-etVBvGAXxfLZCFiIjaLb_4VpSn3r3tAGP2WZJmu4gDLxtWrt_dK_Gq5gH_KzMLOrOxR8fhubWFeCouExQfSOgL19B8eNDT9Qk31bEMSpFmAq2ULVY0UvzdLOSZc0k9WvI-MPzWLjNq7DRCMHrGKqGh0TOjgRMLDPMHukqj5XrU0ypZX002pYA3KUdApTriQTnQIC4N0MdlxAuvdZESSBKZ7tiJ9QDwrF6eWrdl8DiN1kPebPzwNrTK4kwZeGU0gh7ymwAFLiy0DSfuUyA22-ujRSHREtMzoPy7-AdEMYmAL6duLWz-XSKaeVVtPFC31J2I-Gy3IFiUlAWIUuOeKuHfEAcoIf6vPvazg-j7mmp3Le6fJxsh09qOhSdumt6yxE6pdcFR6uqUSf_zyepWOsFK2-TehnSioQTWCjxVglwF6ysgQlYTo8bkuHBlm5mrc4cd8KNiunvt3g.x36wnB6IKa32sgl9LD4n-Q
    npmRegistryServer: "https://fern-dev-985111089818.d.codeartifact.us-east-1.amazonaws.com/npm/fern-dev/"

packageExtensions:
  docsify-cli@*:
    dependencies:
      ansi-colors: "*"
      y18n: "*"
  docsify-server-renderer@*:
    dependencies:
      marked: "*"
      prismjs: "*"
      strip-indent: 3.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
