changesetBaseRefs:
  - main
  - origin/main

npmScopes:
  fern-fern:
    npmRegistryServer: "https://npm-dev.buildwithfern.com/"

packageExtensions:
  "@blueprintjs/eslint-plugin@*":
    dependencies:
      tslib: "*"
  "@blueprintjs/stylelint-plugin@*":
    dependencies:
      tslib: "*"
  docsify-cli@*:
    dependencies:
      ansi-colors: "*"
      y18n: "*"
  docsify-server-renderer@*:
    dependencies:
      marked: "*"
      prismjs: "*"
      strip-indent: 3.0.0
  inquirer-file-tree-selection-prompt@*:
    dependencies:
      inquirer: ^8.0.0
  react-scripts@*:
    dependencies:
      sass-loader: "*"
    peerDependencies:
      sass: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-4.0.0-rc.13.cjs
