version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  lint:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Export Code Artifacts token
          command: export CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token --domain fern-dev --domain-owner 985111089818 --query authorizationToken --output text)"
      - run:
          name: Run code-generation
          command: npm install -g fern-api@0.0.85 && fern generate
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: lint:monorepo
          command: yarn lint:monorepo
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Check dependencies
          command: yarn depcheck
      - run:
          name: lint:eslint
          command: yarn lint:eslint
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff
  compile-and-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Export Code Artifacts token
          command: export CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token --domain fern-dev --domain-owner 985111089818 --query authorizationToken --output text)"
      - run:
          name: Run code-generation
          command: npm install -g fern-api@0.0.85 && fern generate
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Bundle fern-api
          command: yarn workspace @fern-api/cli dist
      - run:
          name: Build fern-typescript docker (for ETE tests)
          command: yarn workspace fern-typescript dockerTagLocal
      - run:
          name: Run tests
          command: yarn test --ci
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff

  publish:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Export Code Artifacts token
          command: export CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token --domain fern-dev --domain-owner 985111089818 --query authorizationToken --output text)"
      - run:
          name: Run code-generation
          command: npm install -g fern-api@0.0.85 && fern generate
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Add version to package.json's
          command: yarn mrlint version $(git tag --points-at HEAD)
      - run:
          name: Update yarn.lock with new versions
          command: yarn
      - run:
          name: Compile
          command: yarn compile:all
      - run:
          name: Publish all packages
          command: yarn run publish
      - run:
          name: Publish fern-api
          command: |
            cd $(yarn workspace @fern-api/cli exec pwd)/webpack
            ./bundle.sh $(git tag --points-at HEAD)
            cd dist
            npm publish
      - run:
          name: Publish fern-typescript docker
          command: |
            projectVersion=$(git tag --points-at HEAD)
            yarn workspace fern-typescript dockerTagVersion
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker push fernapi/fern-typescript:"$projectVersion"

  publish-java-snapshot:
    machine:
      image: ubuntu-2004:current
    environment:
      CIRCLE_TEST_REPORTS: /home/circleci/junit
      CIRCLE_ARTIFACTS: /home/circleci/artifacts
      _JAVA_OPTIONS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false -Xmx8192m
      JAVA_HOME: /opt/java11
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo mkdir -p /opt/java && cd /opt/java && sudo chown -R circleci:circleci .
            curl https://cdn.azul.com/zulu/bin/zulu11.41.23-ca-jdk11.0.8-linux_x64.tar.gz | tar -xzf - -C /opt/java
            sudo ln -s /opt/java/zulu*/ /opt/java11
      - run:
          name: Run code-generation
          command: npm install -g fern-api@0.0.85 && fern generate
      - run:
          name: Publish
          command: |
            export PATH="$PATH:$JAVA_HOME/bin"
            sudo chmod -R 777 packages/compiler/ir-types/fern-ir-java/ir-api/model
            cd packages/compiler/ir-types/fern-ir-java
            ./gradlew artifactoryPublish

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
          context: aws

      - compile-and-test:
          filters:
            tags:
              only: /.*/
          context: aws

      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - lint
            - compile-and-test
          context:
            - npm
            - docker-hub
            - aws

      - publish-java-snapshot:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          context: jfrog
