version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  lint:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: lint:monorepo
          command: yarn lint:monorepo
      - run:
          name: Check root package
          command: yarn check-root-package
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Check dependencies
          command: yarn depcheck
      - run:
          name: lint:eslint
          command: yarn lint:eslint
      - run:
          name: lint:style
          command: yarn lint:style
      - run:
          name: Generate Fern JSON Schema
          command: yarn generate-json-schema
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff
  compile-and-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Run tests
          command: yarn test --ci
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff
  ete-tests:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Run ETE tests
          command: yarn test:ete
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff

  publish-dev:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Print version
          command: |
            git_version="$(./scripts/git-version.sh)"
            echo Publishing version: "${git_version}"
      - run:
          name: Add version to package.json's
          command: yarn mrlint version "$git_version"
      - run:
          name: Publish fern-api CLI (snapshot)
          command: yarn workspace @fern-api/cli publish:cli --access restricted
          environment:
            FERN_CLI_PACKAGE_NAME: fern-api-dev

  pre-release-test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: ETE Test (live)
          command: |
            yarn workspace @fern-api/cli dist
            cli_path="$(yarn workspace @fern-api/cli bin fern)"
            mkdir pre-release-test
            cd pre-release-test

            echo "Running Fern Commands!"
            node $cli_path init --organization fern
            node $cli_path add java
            node $cli_path add typescript
            node $cli_path add postman
            node $cli_path generate

            echo "Cleaning up!"
            cd ..
            rm -rf pre-release-test

  publish:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Print version
          command: |
            git_version="$(./scripts/git-version.sh)"
            echo Publishing version: "${git_version}"
      - run:
          name: Add version to package.json's
          command: yarn mrlint version "$git_version"
      - run:
          name: Update yarn.lock with new versions
          command: yarn
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Publish all packages
          command: yarn run publish
      - run:
          name: Publish fern-api CLI
          command: yarn workspace @fern-api/cli publish:cli

  publish-fern-typescript:
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          name: Publish fern-typescript Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            yarn workspace fern-typescript dockerTagVersion
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker push fernapi/fern-typescript:"$projectVersion"

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/

      - compile-and-test:
          filters:
            tags:
              only: /.*/

      - ete-tests:
          filters:
            tags:
              only: /.*/
          context:
            - auth0-dev

      - publish-dev:
          filters:
            branches:
              only: main
          requires:
            - lint
            - compile-and-test
            - ete-tests
          context:
            - npm
            - auth0-dev

      - pre-release-test:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
          context:
            - auth0-dev

      - publish:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
          requires:
            - lint
            - compile-and-test
            - ete-tests
            - pre-release-test
          context:
            - npm
            - auth0-dev

      - publish-fern-typescript:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
          requires:
            - lint
            - compile-and-test
            - ete-tests
            - pre-release-test
          context:
            - docker-hub
            - auth0-dev
