types:
  GeneratorConfig:
    properties:
      irFilepath: string
      output: optional<GeneratorOutputConfig>
      publish: optional<GeneratorPublishConfig>
      helpers: GeneratorHelpers
  GeneratorOutputConfig:
    properties:
      path: string
  GeneratorPublishConfig:
    properties:
      registries: GeneratorRegistriesConfig
      version: string
  GeneratorRegistriesConfig:
    properties:
      maven: MavenRegistryConfig
      npm: NpmRegistryConfig
  MavenRegistryConfig:
    properties:
      registryUrl: string
      username: string
      password: string
      group: string
      artifactPrefix: string
  NpmRegistryConfig:
    properties:
      registryUrl: string
      token: string
      scope: string
      packagePrefix: string
  GeneratorHelpers:
    properties:
      encodings: map<string, GeneratorHelperReference>
  GeneratorHelperReference:
    properties:
      name: string
      version: string
      absolutePath: string
